import type { Metadata } from "next";
import "./globals.css";
import TopMenuComponent from "@/components/menu/TopMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ru'>
      <body>
        <TopMenuComponent />
        {children}
      </body>
    </html>
  );
}
